# Site
title: Hayden
description: >-
  Sharing thoughts on compilers, embedded systems, and systems programming.
  Passionate about exploring new technologies in computer science.

# Contact
emails:
  - hongcc727@163.com
  - haydenbrwon277@gmail.com
github_username: Hayden727

# Personal
location: Wuhan, China
company: NUDT
avatar: /assets/images/avatar.jpg

# Build
baseurl: ""
url: ""
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
