title: 洪晨辰
email: hongcc727@163.com
description: >- # this means to ignore newlines until "baseurl:"
  欢迎访问我的个人网站！这里记录了我的技术博客、学术成果和项目经验。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 博客专栏设置
blog_categories:
  embedded:
    name: "嵌入式开发"
    subcategories:
      rtos:
        name: "实时操作系统"
      driver:
        name: "驱动开发"
      mcu:
        name: "单片机开发"
  compiler:
    name: "编译技术"
    subcategories:
      llvm:
        name: "LLVM"
      optimization:
        name: "编译优化"
      analysis:
        name: "程序分析"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/
  publications:
    output: true
    permalink: /publications/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

# 自定义设置
avatar: /assets/images/avatar.jpg
theme_color: "#0d47a1"  # 主色调：蓝色
background_color: "#ffffff"  # 背景色：白色 