# 个人信息设置
title: Hayden                    # 你的名字
subtitle: NUDTer                 # 你的头衔/简短描述
description: >-                  # 个人简介
  分享技术、编程和研究的思考。
  热爱探索新技术，专注于计算机科学领域。

# 联系方式
emails: 
  - hongcc727@163.com
  - haydenbrwon277@gmail.com
github_username: Hayden727       # GitHub 用户名

# 个人详细信息
location: Wuhan, China           # 所在地
company: NUDT                    # 公司/组织
avatar: /assets/images/avatar.jpg # 头像路径

# 网站设置
baseurl: ""
url: ""
markdown: kramdown
permalink: /:year/:month/:day/:title/

# 主题设置
theme_color: "#2c5282"          # 主题色
background_color: "#f5f7fa"     # 背景色

# 博客分类
blog_categories:
  compiler:
    name: 编译技术
    subcategories:
      llvm:
        name: LLVM编译框架
      mlir:
        name: MLIR编程模型
      cuda_triton:
        name: CUDA/Triton加速
      deployment:
        name: 推理部署优化
      hardware:
        name: 硬件设计
  embedded:
    name: 嵌入式开发
    subcategories:
      mcu:
        name: 单片机开发
      rtos:
        name: 实时操作系统
